name: Build
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

on:
  push:

jobs:
  build-vs2022:
    runs-on: windows-latest
    steps:
      - name: Import VS2022
        uses: ilammy/msvc-dev-cmd@v1.11.0
        with:
          vsversion: "2022"
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
          cmake -P build-windesktop.cmake
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: vcpkg/nmosh-build-prerequisites-winnative.zip
