name: Build
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

on:
  push:

jobs:
  build-vs2022:
    runs-on: windows-latest
    steps:
      - name: Add nuget source
        run: |
          dotnet nuget add source --username okuoku --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name gh-okuoku https://nuget.pkg.github.com/okuoku/index.json
      - name: Import VS2022
        uses: ilammy/msvc-dev-cmd@v1.11.0
        with:
          vsversion: "2022"
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
          cmake -P build-windesktop.cmake
      - name: Upload package
        run: |
          dotnet nuget push c:\vcpkg\vcpkg-nmosh-prereq-0.1.0.nupkg --api-key ${{ secrets.PAT_PACKAGE }} --source gh-okuoku


