name: Build

on:
  push:

jobs:
  build-vs2019:
    runs-on: windows-latest
    steps:
      - name: Add nuget source
        run: |
          dotnet nuget add source --username okuoku --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name gh-okuoku https://nuget.pkg.github.com/okuoku/index.json
      - name: Import VS2019
        uses: ilammy/msvc-dev-cmd@f6f64f2dd6793f144d0742f2d362a07009dfc2e5
        with:
          vsversion: "2019"
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
          cmake -P build-windesktop.cmake
      - name: Upload package
        run: |
          dotnet nuget push vcpkg\vcpkg-nmosh-prereq-0.1.0.nupkg --api-key ${{ secrets.PAT_PACKAGE }} --source gh-okuoku


